# Generated by Django 4.2.1 on 2023-05-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('birthDate', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50)),
                ('department', models.CharField(choices=[('CS', 'CS'), ('IS', 'IS'), ('AI', 'AI'), ('DS', 'DS'), ('IT', 'IT')], max_length=4)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
