# Generated by Django 4.2.1 on 2023-05-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentAffairsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('birthDate', models.DateField()),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
            ],
        ),
    ]
